### PR TITLE
Added Data Structures Implementation

### PR DESCRIPTION
**Pull request by MananOO12**
I've added implementation of various data structures.

### CODE REVIEW

**Comment by MitanshiKshatriya** [comment]
Hi, thanks for contributing. please follow the file structure mentioned in the README.md for your pull request to be accepted.

like for including heaps in c++ the final path of the file should be - Awesome-DSA/cpp/Data Structures/Heap.cpp

**Comment by MitanshiKshatriya** [comment]
Hi, we have updated our how to contribute guidelines, plz make a pull request according to that.

**Comment by MananOO12** [comment]
> Hi, we have updated our how to contribute guidelines, plz make a pull request according to that.

I've made the necessary changes please look into it.

**Comment by MitanshiKshatriya** [comment]
Hi, thanks for your contribution and for raising an issue which will for sure make our repo more organized!

**Pull request merged**
