### PR TITLE
BinarySearch on JS

### PR DESCRIPTION
**Pull request by niobiumneo**

### CODE REVIEW

**Comment by niobiumneo** [comment]
Just created a BinarySearch alg on JS. Let me know if i did something wrong

**Comment by MitanshiKshatriya** [comment]
Hi, just remove the BinarySearch.js file from the root folder.
Then your PR will be accepted.

**Comment by niobiumneo** [comment]
Root folder as in the main folder of the DSA right? I just did that

**Comment by MitanshiKshatriya** [comment]
Yes thats what i meant. Thankyou for your contribution!

**Comment by niobiumneo** [comment]
Do we need to like post a ss to hacktoberfest for this to be a valid PR?

**Comment by MitanshiKshatriya** [comment]
no thats not needed. Have you logged in to hacktoberfest website?
If you have logged in using your github account it will reflect on the website that you have made ur PR.

**Comment by niobiumneo** [comment]
Yes just saw it, thanks!

**Pull request merged**
